### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by swc42** [MayurDivate/GUAVA#18]
When I run data analysis in GUAVA, I keep getting this warning and I never see the tabular output interface window. Is there anyone who can provide suggestions on how I can fix this?
[awd2056a:GUAVA-1 chungs1$ java -jar GUAVA.jar
GUAVA version 1
Operating System of machine :Mac OS X
		cutadapt:		Working!
		bowtie:		Working!
		bowtie2:	Working!
		fastqc:		Working!
		samtools:	Working!
		macs2:		Working!
		Picard:		Working!
		bedtools:		Working!
		bedGraphToBigWig:		Working!
		igv:		Working!
fastq QC...
Alignment...
Please wait while bowtie2 alignment is finished..Done!
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.poi.util.DocumentHelper (file:/Users/chungs1/GUAVA-1/lib/poi-ooxml-3.16-beta2.jar) to method com.sun.org.apache.xerces.internal.util.SecurityManager.setEntityExpansionLimit(int)
WARNING: Please consider reporting this to the maintainers of org.apache.poi.util.DocumentHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
---- Alignment filtering ------
Remove duplicates...Done!
Filter [chr6] reads...
No chr found for idxstats	
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at umac.guava.Samtools.getReadCount(Samtools.java:253)
	at umac.guava.AnalysisWorkflow.runAlignmentFiltering(AnalysisWorkflow.java:570)
	at umac.guava.AnalysisWorkflow.startGUIGuavaAnalysis(AnalysisWorkflow.java:166)
	at umac.guava.MainJFrame.startJButtonActionPerformed(MainJFrame.java:837)
	at umac.guava.MainJFrame.access$700(MainJFrame.java:27)
	at umac.guava.MainJFrame$8.actionPerformed(MainJFrame.java:267)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by MayurDivate** [comment]
@swc42 

"The illegal reflective access" is a Java  9 problem.
I never faced it before. I will try my best to solve it.

But to help you with the alignment filtering problem.
could you please share the log file?

Thanks,
Mayur

**Comment by Shirayuki-hub** [comment]
Hi, I am having a similar issue here. Could you please help me?

$ java -jar GUAVA.jar
GUAVA version 1
Operating System of machine :Mac OS X
		cutadapt:		Working!
		bowtie:		Working!
		bowtie2:	Working!
		fastqc:		Working!
		samtools:	Working!
		macs2:		Working!
		Picard:		Working!
		bedtools:		Working!
		bedGraphToBigWig:		Working!
		igv:		Working!
Adapter trimming...Done
fastq QC...
Alignment...
Please wait while bowtie2 alignment is finished..Done!
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.poi.util.DocumentHelper (file:/Users/GUAVA-1/lib/poi-ooxml-3.16-beta2.jar) to method com.sun.org.apache.xerces.internal.util.SecurityManager.setEntityExpansionLimit(int)
WARNING: Please consider reporting this to the maintainers of org.apache.poi.util.DocumentHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
---- Alignment filtering ------
Remove duplicates...Done!
Filter [chr1] reads...
Filter [chr10] reads...
Filter [chr11] reads...
Filter [chr11_gl000202_random] reads...
Filter [chr12] reads...
Filter [chr13] reads...
Filter [chr14] reads...
Filter [chr15] reads...
Filter [chr16] reads...
Filter [chr17] reads...
Filter [chr17_ctg5_hap1] reads...
Filter [chr17_gl000203_random] reads...
Filter [chr17_gl000204_random] reads...
Filter [chr17_gl000205_random] reads...
Filter [chr17_gl000206_random] reads...
Filter [chr18] reads...
Filter [chr18_gl000207_random] reads...
Filter [chr19] reads...
Filter [chr19_gl000208_random] reads...
Filter [chr19_gl000209_random] reads...
Filter [chr1_GL456210_random] reads...
Filter [chr1_GL456211_random] reads...
Filter [chr1_GL456212_random] reads...
Filter [chr1_GL456213_random] reads...
Filter [chr1_GL456221_random] reads...
Filter [chr1_gl000191_random] reads...
Filter [chr1_gl000192_random] reads...
Filter [chr2] reads...
Filter [chr20] reads...
Filter [chr21] reads...
Filter [chr21_gl000210_random] reads...
Filter [chr22] reads...
Filter [chr3] reads...
Filter [chr4] reads...
Filter [chr4_GL456216_random] reads...
Filter [chr4_GL456350_random] reads...
Filter [chr4_JH584292_random] reads...
Filter [chr4_JH584293_random] reads...
Filter [chr4_JH584294_random] reads...
Filter [chr4_JH584295_random] reads...
Filter [chr4_ctg9_hap1] reads...
Filter [chr4_gl000193_random] reads...
Filter [chr4_gl000194_random] reads...
Filter [chr5] reads...
Filter [chr5_GL456354_random] reads...
Filter [chr5_JH584296_random] reads...
Filter [chr5_JH584297_random] reads...
Filter [chr5_JH584298_random] reads...
Filter [chr5_JH584299_random] reads...
Filter [chr6_apd_hap1] reads...
Filter [chr6_cox_hap2] reads...
Filter [chr6_dbb_hap3] reads...
Filter [chr6_mann_hap4] reads...
Filter [chr6_mcf_hap5] reads...
Filter [chr6_qbl_hap6] reads...
Filter [chr6_ssto_hap7] reads...
Filter [chr7] reads...
Filter [chr7_GL456219_random] reads...
Filter [chr7_gl000195_random] reads...
Filter [chr8] reads...
Filter [chr8_gl000196_random] reads...
Filter [chr8_gl000197_random] reads...
Filter [chr9] reads...
Filter [chr9_gl000198_random] reads...
Filter [chr9_gl000199_random] reads...
Filter [chr9_gl000200_random] reads...
Filter [chr9_gl000201_random] reads...
Filter [chrM] reads...
Filter [chrUn_GL456239] reads...
Filter [chrUn_GL456359] reads...
Filter [chrUn_GL456360] reads...
Filter [chrUn_GL456366] reads...
Filter [chrUn_GL456367] reads...
Filter [chrUn_GL456368] reads...
Filter [chrUn_GL456370] reads...
Filter [chrUn_GL456372] reads...
Filter [chrUn_GL456378] reads...
Filter [chrUn_GL456379] reads...
Filter [chrUn_GL456381] reads...
Filter [chrUn_GL456382] reads...
Filter [chrUn_GL456383] reads...
Filter [chrUn_GL456385] reads...
Filter [chrUn_GL456387] reads...
Filter [chrUn_GL456389] reads...
Filter [chrUn_GL456390] reads...
Filter [chrUn_GL456392] reads...
Filter [chrUn_GL456393] reads...
Filter [chrUn_GL456394] reads...
Filter [chrUn_GL456396] reads...
Filter [chrUn_JH584304] reads...
Filter [chrUn_gl000211] reads...
Filter [chrUn_gl000212] reads...
Filter [chrUn_gl000213] reads...
Filter [chrUn_gl000214] reads...
Filter [chrUn_gl000215] reads...
Filter [chrUn_gl000216] reads...
Filter [chrUn_gl000217] reads...
Filter [chrUn_gl000218] reads...
Filter [chrUn_gl000219] reads...
Filter [chrUn_gl000220] reads...
Filter [chrUn_gl000221] reads...
Filter [chrUn_gl000222] reads...
Filter [chrUn_gl000223] reads...
Filter [chrUn_gl000224] reads...
Filter [chrUn_gl000225] reads...
Filter [chrUn_gl000226] reads...
Filter [chrUn_gl000227] reads...
Filter [chrUn_gl000228] reads...
Filter [chrUn_gl000229] reads...
Filter [chrUn_gl000230] reads...
Filter [chrUn_gl000231] reads...
Filter [chrUn_gl000232] reads...
Filter [chrUn_gl000233] reads...
Filter [chrUn_gl000234] reads...
Filter [chrUn_gl000235] reads...
Filter [chrUn_gl000236] reads...
Filter [chrUn_gl000237] reads...
Filter [chrUn_gl000238] reads...
Filter [chrUn_gl000239] reads...
Filter [chrUn_gl000240] reads...
Filter [chrUn_gl000241] reads...
Filter [chrUn_gl000242] reads...
Filter [chrUn_gl000243] reads...
Filter [chrUn_gl000244] reads...
Filter [chrUn_gl000245] reads...
Filter [chrUn_gl000246] reads...
Filter [chrUn_gl000247] reads...
Filter [chrUn_gl000248] reads...
Filter [chrUn_gl000249] reads...
Filter [chrX] reads...
Filter [chrX_GL456233_random] reads...
Filter [chrY] reads...
Filter [chrY_JH584300_random] reads...
Filter [chrY_JH584301_random] reads...
Filter [chrY_JH584302_random] reads...
Filter [chrY_JH584303_random] reads...
No chr found for idxstats	
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at umac.guava.Samtools.getReadCount(Samtools.java:253)
	at umac.guava.AnalysisWorkflow.runAlignmentFiltering(AnalysisWorkflow.java:570)
	at umac.guava.AnalysisWorkflow.startGUIGuavaAnalysis(AnalysisWorkflow.java:166)
	at umac.guava.MainJFrame.startJButtonActionPerformed(MainJFrame.java:837)
	at umac.guava.MainJFrame.access$700(MainJFrame.java:27)
	at umac.guava.MainJFrame$8.actionPerformed(MainJFrame.java:267)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by jademcdaniel** [comment]
Hi! Thanks so much for all the work you've put into this program--it's made ATAC-seq analysis much easier for someone who is a beginner with sequencing analysis. 

I've been having this same issue as listed above and I was wondering if you ever figured out a work-around. Here is what I'm seeing:

(base) drigo@drigo-Precision-5820-Tower:~$ cd ~/GUAVA-1.0.1
(base) drigo@drigo-Precision-5820-Tower:~/GUAVA-1.0.1$ java -jar GUAVA.jar
GUAVA version 1
Operating System of machine :Linux
		cutadapt:		Working!
		bowtie:		Working!
		bowtie2:	Working!
		fastqc:		Working!
		samtools:	Working!
		macs2:		Working!
		Picard:		Working!
		bedtools:		Working!
		bedGraphToBigWig:		Working!
		igv:		Working!
Adapter trimming...Done
fastq QC...
Alignment...
Please wait while bowtie2 alignment is finished..Done!
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.poi.util.DocumentHelper (file:/home/drigo/GUAVA-1.0.1/lib/poi-ooxml-3.16-beta2.jar) to method com.sun.org.apache.xerces.internal.util.SecurityManager.setEntityExpansionLimit(int)
WARNING: Please consider reporting this to the maintainers of org.apache.poi.util.DocumentHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
---- Alignment filtering ------
Remove duplicates...Done!
Filter [chrM] reads...
No chr found for idxstats	
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at umac.guava.Samtools.getReadCount(Samtools.java:253)
	at umac.guava.AnalysisWorkflow.runAlignmentFiltering(AnalysisWorkflow.java:570)
	at umac.guava.AnalysisWorkflow.startGUIGuavaAnalysis(AnalysisWorkflow.java:166)
	at umac.guava.MainJFrame.startJButtonActionPerformed(MainJFrame.java:837)
	at umac.guava.MainJFrame.access$700(MainJFrame.java:27)
	at umac.guava.MainJFrame$8.actionPerformed(MainJFrame.java:267)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6589)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6354)
	at java.desktop/java.awt.Container.processEvent(Container.java:2261)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4966)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2319)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4914)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4543)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4484)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2305)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

I've attached the log file as well, but let me know if you need anything else.

[7315-JM-2_S1_L005_R1_001_log.txt](https://github.com/MayurDivate/GUAVA/files/7908245/7315-JM-2_S1_L005_R1_001_log.txt)
